project_models = "/app/project_models"
project_infra = "/app/project_infra"

[log]
level = "debug"
output = "Console"
output_path = "./logs/"

[web]
host = "0.0.0.0"
port = 8081

[database]
url = "sqlite:///data/wp-station/station.db"
max_connections = 10
min_connections = 2
connect_timeout = 30
idle_timeout = 600

[gitea]
base_url = "http://gitea:3000"
username = "gitea"
password = "123456"

[features]
data_collect_url = "http://localho231232st:18081/wp-monitor"
