import { createStaticHighlightExtension } from './staticHighlight';

const excludedPatterns = [
  /\/\/.*/g,
  /"(?:[^"\\]|\\.)*"/g,
];

const WFL_KEYWORDS = [
  'use',
  'pattern',
  'rule',
  'test',
  'scenario',
  'if',
  'then',
  'else',
  'meta',
  'events',
  'match',
  'on',
  'each',
  'where',
  'event',
  'close',
  'and',
  'join',
  'entity',
  'yield',
  'score',
  'key',
  'conv',
  'limits',
  'for',
  'input',
  'expect',
  'options',
  'traffic',
  'stream',
  'gen',
  'injection',
  'near_miss',
  'miss',
  'precision',
  'recall',
  'fpr',
  'latency_p95',
  'seq',
  'not',
  'row',
  'tick',
  'hits',
  'hit',
  'origin',
  'fixed',
  'within',
  'in',
  'snapshot',
  'asof',
  'anti',
  'session',
];

const WFL_BUILTINS = [
  'count',
  'sum',
  'avg',
  'min',
  'max',
  'distinct',
  'fmt',
  'baseline',
  'has',
  'contains',
  'regex_match',
  'startswith',
  'endswith',
  'len',
  'lower',
  'upper',
  'time_diff',
  'time_bucket',
  'coalesce',
  'mvcount',
  'collect_set',
  'collect_list',
  'first',
  'last',
  'stddev',
  'percentile',
  'sort',
  'top',
  'dedup',
];

const keywordPattern = new RegExp(`\\b(?:${WFL_KEYWORDS.join('|')})\\b`, 'g');
const builtinPattern = new RegExp(`\\b(?:${WFL_BUILTINS.join('|')})\\b(?=\\s*\\()`, 'g');

const rules = [
  { pattern: /\/\/.*/g, className: 'cm-wf-comment' },
  { pattern: /"(?:[^"\\]|\\.)*"/g, className: 'cm-wf-string' },
  { pattern: keywordPattern, className: 'cm-wf-keyword' },
  { pattern: builtinPattern, className: 'cm-wf-function' },
  { pattern: /\b(?:true|false)\b/g, className: 'cm-wf-special' },
  { pattern: /@[A-Za-z_][A-Za-z0-9_]*/g, className: 'cm-wf-special' },
  { pattern: /\b(?:_in|close_reason)\b/g, className: 'cm-wf-special' },
  { pattern: /\b\d+(?:\.\d+)?(?:ms|s|m|h|d)\b/g, className: 'cm-wf-number' },
  { pattern: /\b\d+(?:\.\d+)?%/g, className: 'cm-wf-number' },
  { pattern: /\b\d+(?:\.\d+)?\/s\b/g, className: 'cm-wf-number' },
  { pattern: /\b\d+(?:\.\d+)?\b/g, className: 'cm-wf-number' },
  { pattern: /\b[A-Za-z_][A-Za-z0-9_]*\b(?=\s*\()/g, className: 'cm-wf-function' },
  { pattern: /(?<=\.)[A-Za-z_][A-Za-z0-9_]*/g, className: 'cm-wf-property' },
  { pattern: /\b[A-Za-z_][A-Za-z0-9_]*\b(?=\s*=)/g, className: 'cm-wf-property' },
  { pattern: /\b(?:rule|pattern|test|scenario)\s+[A-Za-z_][A-Za-z0-9_]*/g, className: 'cm-wf-function' },
  { pattern: /\b[A-Za-z_][A-Za-z0-9_]*\b(?=\s*:\s*[A-Za-z_][A-Za-z0-9_]*)/g, className: 'cm-wf-variable' },
  { pattern: /\b(?:drop_oldest|throttle)\b/g, className: 'cm-wf-type' },
  { pattern: /(?:\|>|\->|&&|\|\||==|!=|<=|>=|[+\-*/%|])/g, className: 'cm-wf-operator' },
  { pattern: /[@()[\]{}.,;:<>]/g, className: 'cm-wf-punctuation' },
];

export function wflHighlightExtension() {
  return createStaticHighlightExtension({
    excludedPatterns,
    rules,
  });
}
